[2021-03-23 15:33:01,364] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: data_prep_and_process.data_preperation 2021-03-23T09:57:15.116028+00:00 [queued]>
[2021-03-23 15:33:01,368] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: data_prep_and_process.data_preperation 2021-03-23T09:57:15.116028+00:00 [queued]>
[2021-03-23 15:33:01,368] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-23 15:33:01,368] {taskinstance.py:1043} INFO - Starting attempt 2 of 2
[2021-03-23 15:33:01,368] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-23 15:33:01,376] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): data_preperation> on 2021-03-23T09:57:15.116028+00:00
[2021-03-23 15:33:01,379] {standard_task_runner.py:52} INFO - Started process 42627 to run task
[2021-03-23 15:33:01,387] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'data_prep_and_process', 'data_preperation', '2021-03-23T09:57:15.116028+00:00', '--job-id', '38', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/master_dag.py', '--cfg-path', '/var/folders/yw/952dv3rd0332_2c7vqyq34vc0000gp/T/tmpel7ox4om', '--error-file', '/var/folders/yw/952dv3rd0332_2c7vqyq34vc0000gp/T/tmp2_aq_hla']
[2021-03-23 15:33:01,390] {standard_task_runner.py:77} INFO - Job 38: Subtask data_preperation
[2021-03-23 15:33:06,436] {logging_mixin.py:104} INFO - Running <TaskInstance: data_prep_and_process.data_preperation 2021-03-23T09:57:15.116028+00:00 [running]> on host FACT-LAP-135.local
[2021-03-23 15:33:11,479] {taskinstance.py:1255} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=skadhithya95@example.com
AIRFLOW_CTX_DAG_OWNER=adhithya
AIRFLOW_CTX_DAG_ID=data_prep_and_process
AIRFLOW_CTX_TASK_ID=data_preperation
AIRFLOW_CTX_EXECUTION_DATE=2021-03-23T09:57:15.116028+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-03-23T09:57:15.116028+00:00
[2021-03-23 15:33:11,483] {data_preparation.py:54} INFO - URL to fetch records --> https://api.exchangeratesapi.io/history?start_at=2018-01-01&end_at=2021-03-23

[2021-03-23 15:33:11,484] {data_preparation.py:57} INFO - Get request --> hitting the URL to fetch data
[2021-03-23 15:33:11,658] {data_preparation.py:59} INFO - Get request ::: Status --> Successful

[2021-03-23 15:33:11,674] {data_preparation.py:66} INFO - Display sample records fetched from URL

[2021-03-23 15:33:11,676] {logging_mixin.py:104} INFO - {'CAD': 1.5466, 'HKD': 9.0327, 'ISK': 163.5, 'PHP': 56.407, 'DKK': 7.4455, 'HUF': 366.24, 'CZK': 27.131, 'AUD': 1.6533, 'RON': 4.8674, 'SEK': 10.3625, 'IDR': 17064.82, 'INR': 86.7555, 'BRL': 6.6916, 'RUB': 93.745, 'HRK': 7.5695, 'JPY': 121.93, 'THB': 36.249, 'CHF': 1.0695, 'SGD': 1.5903, 'PLN': 4.6018, 'BGN': 1.9558, 'TRY': 9.8332, 'CNY': 7.7962, 'NOK': 11.1128, 'NZD': 1.7565, 'ZAR': 18.8972, 'USD': 1.1652, 'MXN': 24.7327, 'ILS': 3.9681, 'GBP': 0.90053, 'KRW': 1320.61, 'MYR': 4.8443}
[2021-03-23 15:33:11,677] {logging_mixin.py:104} INFO - 
[2021-03-23 15:33:11,774] {data_preparation.py:143} INFO - Pushing JSON file to Local drive - Path ::: /Users/adhithyakarthikeyan/currency_hist_records.json

[2021-03-23 15:33:11,923] {data_preparation.py:147} INFO - Status ::: Succcessful --> Currency historical records Path ::: /Users/adhithyakarthikeyan/currency_hist_records.json

[2021-03-23 15:33:11,926] {data_preparation.py:180} INFO - Filtering historical data for currencies
[2021-03-23 15:33:11,927] {data_preparation.py:190} INFO - required_currencies['EUR', 'USD', 'JPY', 'CAD', 'GBP', 'NZD', 'INR']
[2021-03-23 15:33:11,933] {data_preparation.py:202} INFO - Status successful --> Filtered records
[2021-03-23 15:33:11,935] {python.py:118} INFO - Done. Returned value was: <data_preparation.data_preparation object at 0x7ffaeb3a64c0>
[2021-03-23 15:33:11,941] {taskinstance.py:1159} INFO - Marking task as SUCCESS. dag_id=data_prep_and_process, task_id=data_preperation, execution_date=20210323T095715, start_date=20210323T100301, end_date=20210323T100311
[2021-03-23 15:33:11,971] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-03-23 15:33:12,021] {local_task_job.py:146} INFO - Task exited with return code 0
